### ISSUE TITLE
Add arm64 compiler compatibility table 

### ISSUE THREAD

**Issue by haoyu01** [intel/isa-l#107]
@gbtucker , I found there are many compatibility issues . 

I plan to add a document about it . What's your suggestion ? 
- Should I add a table about the compiler issues and how to fix it .
- Or add minimal requirement of Arm .
And where can I add it ? README.md or a new file ?

**Comment by gbtucker** [comment]
Sounds like the compiler compatibility issue is simply that most of the asm is written to the requirements of the gnu assembler (gas) and not the more restrictive clang integrated assembler.  Adding `-fno-integrated-as` to clang just calls gas so gas is still a dependency.  Instead of making it complicated with a table of gcc/clang combinations, just consider gcc the min requirement for arm as it is.  We should remove clang arm from travis and drone.io until either clang finishes adding gas extensions, or the code is updated to use clang asm.

**Comment by haoyu01** [comment]
@gbtucker ， relative patch has been merged . Close this issue . 
Now we will not support clang for Arm64 .
