### ISSUE TITLE
Why apply isa-l to gzip instead of lz4?

### ISSUE THREAD

**Issue by yongw-pur** [intel/isa-l#146]
Why apply isa-l to gzip instead of lz4

**Comment by gbtucker** [comment]
Thanks @yongw-pur.  It is a good question.  LZ4 is certainly fast but has limitations on compression ratio due to no entropy encoding performed.  It is also very simple and limited optimizations are possible.  Isa-l compression can approach the encode speed of lz4 with much better compression ratio.

**Comment by yongw-pur** [comment]
> Thanks @yongw-pur. It is a good question. LZ4 is certainly fast but has limitations on compression ratio due to no entropy encoding performed. It is also very simple and limited optimizations are possible. Isa-l compression can approach the encode speed of lz4 with much better compression ratio.

Thank you!
