### ISSUE TITLE
isal_inflate (igzip_inflate.c) bug when state->crc_flag == IGZIP_GZIP or IGZIP_ZLIB

### ISSUE THREAD

**Issue by bli25** [intel/isa-l#224]
The gz_hdr or z_hdr are local within in the function. Thus, if the header cannot be read in fully in one time, the header information will be missing for the next time to ingest rest of header information. 

In particular for gzip header, because the flags is not initialized, it is possible for the "next time" to get random flags and then lead to incorrect ingestion of the buffer.

**Comment by gbtucker** [comment]
I think the issue is that if you want to keep any of the fields in the gzip header then you must consume with isal_read_gzip_header() instead of relying on isal_inflate() to skip and throw out these fields it doesn't care about.  Also if you rely on isal_inflate() to consume the gzip header, you must give the initial buffer a whole header at a time.

**Comment by bli25** [comment]
@gbtucker , I agree. Can you update the documentation to make this clear?

**Comment by gbtucker** [comment]
Yes, thank you @bli25.  We will update the documentation on this to make clear.
