### ISSUE TITLE
why TEST_SOURCES 32 in erasure_code_perf.c?

### ISSUE THREAD

**Issue by mengwanguc** [intel/isa-l#229]
Hello,

I see in erasure_code_perf.c, it defines `TEST_SOURCES` as 32. 

And it let `MMAX` = `TEST_SOURCES`. And if `m > MMAX`, it prints "Input test parameter error".

But why 32? Is there a specific reason?
Doesn't isa-l support m>32? I believe it should support.

**Comment by gbtucker** [comment]
Hi @mengwanguc.  Yes, isa-l does support m > 32.  For the performance test we just pick one common set of parameters and keep it easy to adjust this within a small range.
```
        // Pick test parameters
        m = 14;
        k = 10;
        nerrs = 4;
```
These can be adjusted up to MMAX which is set to 32 just to keep stack structures small that otherwise could be m x k in size.  If you change MMAX then you might want to allocate these from the heap instead but any size of encoding is supported.

**Comment by mengwanguc** [comment]
Makes sense to me. Thank you!
