### ISSUE TITLE
Is this condition correct?

### ISSUE THREAD

**Issue by Apollo3zehn** [intel/isa-l#253]
I think the following line from function `compress_file()` 

https://github.com/intel/isa-l/blob/e53db8563180712ec5f1759ec9d52b844c86fa30/programs/igzip_cli.c#L779

should actually be:

```c
... || stream.avail_out != 0); 
```
(The condition is now `!=` instead of  `==`).

And I would say the same applies to the function `decompress_file()`:

https://github.com/intel/isa-l/blob/e53db8563180712ec5f1759ec9d52b844c86fa30/programs/igzip_cli.c#L943

With the original condition (`avail_out == 0`), the loop continues to run without being able to progress because the output buffer is full.

**Comment by pablodelara** [comment]
@Apollo3zehn, I think the condition is OK. At that point, avail_out indicates how many byte are still available to be written in the output (so basically, it indicates if the output buffer has been totally used). But the buffer is used again in the next iteration (see lines 763-764), as avail_out is set to outbuf_size again. So basically this condition is useful in case the input file has been fully read, but there might be some bytes left to write because all bytes in output buffer have been written. Hope this is understood.

**Comment by pablodelara** [comment]
Closing this issue. Feel free to open it if you think there is still an issue, thanks.

**Comment by Apollo3zehn** [comment]
Thank you, I understand now. The condition make sense if the buffer is being reused or resized to hold more data.
