### ISSUE TITLE
Add Rust language bindings

### ISSUE THREAD

**Issue by milesgranger** [intel/isa-l#300]
Hello,

FWIW, I have perhaps not terrible Rust bindings  at https://github.com/milesgranger/isal-rs
Maybe it can be added to the wiki https://github.com/intel/isa-l/wiki/Language-Bindings?

**Comment by rhpvorderman** [comment]
Hi, python-isal maintainer here. Since flate2 is the "default" gzip/zlib interface in rust. (At least it is in the rust-lang github group). I recommend copying its interface. That way people can switch to your crate with minimal adaptation to the code. That will improve adoption. (if you care about that sort of thing).

**Comment by milesgranger** [comment]
> That will improve adoption. (if you care about that sort of thing).

Hehe, of course I care. :wink: It does implement `Read/Write` for the encoder/decoders same as flate2, so I'd say it's well on its way to a similar API; I suppose we shouldn't get to deep into this, it's not at all relevant to this issue here I think.

**Comment by pablodelara** [comment]
Done: https://github.com/intel/isa-l/wiki/Language-Bindings
