### ISSUE TITLE
build break on x86_64 centos7

### ISSUE THREAD

**Issue by haoyu01** [intel/isa-l#77]
build isa-l with `make -f Makefile.unx` on centos7 . It reports 
```bash
[haoyu01@762e95a388af isa-l]$ make -f Makefile.unx
  ---> Building crc/crc16_t10dif_01.asm  x86_64
crc/crc16_t10dif_01.asm:330: error: invalid combination of opcode and operands
make: *** [bin/crc16_t10dif_01.o] Error 1
[haoyu01@762e95a388af isa-l]$ nasm -v
NASM version 2.10.07 compiled on Jun  9 2014
```
It is nasm version issue . nasm version is 2.10.7 . And 2.14.2 is okay .
isa-l is the master branch .

**Comment by gbtucker** [comment]
Yes, the minimum nasm version required is v2.11.01 although v2.13 or newer is recommended.

If this worked before it may be because we changed the default in the std. makefile from yasm to nasm and you may have had an above minimum yasm installed.  You can always change the default with `make -f Makefile.unx AS=yasm` but I would recommend upgrading to a modern nasm instead.

**Comment by haoyu01** [comment]
Thanks . I have upgrade nasm to 2.14.2
